server:
  port: 8092
  servlet:
    context-path: /api/transfer

management:
  server:
    port: 8191
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 12345

  liquibase:
    default-schema: transfer
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: transfer-app

eureka:
  instance:
    hostname: transfer
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



